#!/bin/bash
echo "=== Firebase Storage Manual Setup Required ==="
echo ""
echo "Firebase Storage must be manually initialized through the console:"
echo "1. Go to: https://console.firebase.google.com/project/diagnostic-pro-prod/storage"
echo "2. Click 'Get Started'"  
echo "3. Accept default settings (creates bucket: diagnostic-pro-prod.appspot.com)"
echo "4. Return here and run: npx firebase deploy --only storage:rules"
echo ""
echo "This creates the default storage bucket required for the deployment."
echo ""
echo "After manual setup, storage will be ready for:"
echo "- PDF report uploads"
echo "- Signed URL downloads" 
echo "- Security rules deployment"
