// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { isFeatureEnabled } from "@/config/feature-flags";

const SUPABASE_URL = "https://jjxvrxehmawuyxltrvql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqeHZyeGVobWF3dXl4bHRydnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzUxNzMsImV4cCI6MjA3MDk1MTE3M30.lZVeWlfnHHcXUq-i3c6V23R_ibUZJpELPhU-7W6lR3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// ⚠️ DEPRECATED: Supabase client disabled for Cloud Run migration
// Use cloudRunClient from @/services/cloud-run-client instead
export const supabase = isFeatureEnabled('USE_SUPABASE')
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : null as any; // Disabled for migration
